### ISSUE TITLE
Dynamic reconfigure support

### ISSUE THREAD

**Issue by bit-pirate** [DLu/navigation_layers#11]
The standard plugins (https://github.com/ros-planning/navigation/tree/hydro-devel/costmap_2d/cfg) already support this.

Would be very convenient to have dynamic reconfigure support for the range sensor layer as well.

**Comment by trainman419** [comment]
I'm sure David would welcome a pull request that adds dynamic_reconfigure support.

**Comment by bit-pirate** [comment]
> I'm sure David would welcome a pull request that adds dynamic_reconfigure support.

I know. :smiling_imp: I'll try to get one put together, when I find some time to implement this myself.

**Comment by DLu** [comment]
Initial branch posted. Take a look let me know what you think.

**Comment by corot** [comment]
I merged the changes into my [master branch](https://github.com/corot/navigation_layers) and it works fine. :+1: for merging into indigo. Only thing I would change is to remove max_angle parameter, as it is continuously overwritten withe the Range message field_of_view field

**Comment by DLu** [comment]
Merged into hydro and indigo.
