### ISSUE TITLE
Why is RangeSensorLayer not an ObstacleLayer?

### ISSUE THREAD

**Issue by bit-pirate** [DLu/navigation_layers#13]
After looking further into the code I started wondering why the `RangeSensorLayer` is not an (does not inherit from) `ObstacleLayer`. IMO there is a lot of interesting functionality already implemented in the obstacle layer, e.g. clearing and marking.

Is there a specfic reason for this design choice?

**Comment by DLu** [comment]
The primary difference is that RangeSensorLayer calculates values probabilistically, whereas ObstacleLayer assumes high accuracy data. If you'd like to use the Range message type with the ObstacleLayer, the easiest approach would be to convert it to a point cloud.
