### ISSUE TITLE
Local costmap_ update done on callback

### ISSUE THREAD

**Issue by AlexReimann** [DLu/navigation_layers#15]
Hey,
the updating of the costmap of the RangeSensorLayer is done in the callback function (incomingRange). The ObstacleLayer and VoxelLayer both update in the updateBounds function using the observation buffer.

What was the reasoning for not implementing it the same way?

@DLu

**Comment by AlexReimann** [comment]
One issue I see with this is that the updateOrigin function gets called after the messages are inserted into the costmap_.

**Comment by DLu** [comment]
No particular reason, other than simplicity. In the situation you described, I suppose the edges of a local costmap could be erroneously empty, right? 

It probably makes more sense to queue them up.

**Comment by AlexReimann** [comment]
Also the position of the obstacles could be wrong a bit if the robot is moving I guess?

[Patch AlexReimann@  9674319](https://github.com/AlexReimann/navigation_layers/commit/9674319449f9069915708bf45fbb738f0c421432)

**Comment by DLu** [comment]
Looks good. PR it.
