### ISSUE TITLE
If range sensor layer is disabled with dynamic reconfigure, the robot stops moving 

### ISSUE THREAD

**Issue by corot** [DLu/navigation_layers#20]
Move base complains (correctly) that the data is no up to date and shows this warning continuously:

```
[/move_base]:Sensor data is out of date, we're not going to allow commanding of the base for safety
```

**Comment by DLu** [comment]
Hey @corot  - please try the current_checks branch to see if that fixes the problem.

**Comment by corot** [comment]
:+1:  solved!

**Comment by corot** [comment]
@DLu, can you merge on indigo so we can close this?

**Comment by DLu** [comment]
Hydro: #21 

Indigo: 5dcf6c4bbfb2ae411e6936ffabd2d66bafcdf30e
