### ISSUE TITLE
Inverted velocity in social navigation layer

### ISSUE THREAD

**Issue by cdondrup** [DLu/navigation_layers#25]
We (@jmcjacob and I) came across a weird issue with the calculation of the Gaussian representing the human in the social navigation layer. The velocity of the human was inverted which is why the Gaussian was extended behind the human instead of in front when moving towards the robot. We narrowed it down to what we think might be the issue. The [calculation of the velocity](https://github.com/strands-project/navigation_layers/blob/indigo/social_navigation_layers/src/social_layer.cpp#L52-L54) should be the other way around:

```
tpt.velocity.x = opt.point.x - tpt.position.x;
tpt.velocity.y = opt.point.y - tpt.position.y;
tpt.velocity.z = opt.point.z - tpt.position.z;
```

Because by [adding the velocity to the position](https://github.com/strands-project/navigation_layers/blob/indigo/social_navigation_layers/src/social_layer.cpp#L47-L49) and then [subtracting the velocity from the position](https://github.com/strands-project/navigation_layers/blob/indigo/social_navigation_layers/src/social_layer.cpp#L52-L54) instead of subtracting the position from the velocity (as described above), the velocity is inverted.

Maybe there is an oversight on our side but currently the social layer will always be extended behind the human. If this indeed a bug, we can open a PR fixing it as we have it working on our robot. If it is not, then I would be grateful for a hint where we might be wrong.

**Comment by DLu** [comment]
I finally had a chance to look at this. This definitely seems counter intuitive. I'm sure it worked for me at some point, but I think it should be changed. Pull request welcome.

**Comment by cdondrup** [comment]
I think this can be closed closed then. Thank you!
