### ISSUE TITLE
How to add navigation_layer to the existing navigation stack

### ISSUE THREAD

**Issue by guchaojie** [DLu/navigation_layers#35]
There is any README for user to integrate navigation_layer into navigation stack in ROS.
In my understanding, we have to add these files separately into costmap_2d directory such as cfg , include and src directory structure one by one.

And in src/costmap_2d_ros.cpp:
void Costmap2DROS::resetOldParameters(ros::NodeHandle& nh)  in this function. We add
 your naviagtion_layer plugin into map, it will work out , right ?

For social layer to detect person ,  what kind of phyiscal sensor to do that?  If there is a moving things around robot, suppose that social layer also can work out to avoid them , right ?

**Comment by DLu** [comment]
http://wiki.ros.org/costmap_2d/Tutorials/Configuring%20Layered%20Costmaps

Also, answers.ros.org is the more appropriate venue for this kind of inquiry.
