### ISSUE TITLE
range sensor layer: Undocumented max_angle parameter

### ISSUE THREAD

**Issue by nxdefiant** [DLu/navigation_layers#36]
In the range sensor layer there is a dynamic reconfigure parameter "max_angle" which is undocumented in the wiki. It doesn't seem to do anything useful as it is overwritten by "range_message.field_of_view/2" in RangeSensorLayer::updateCostmap().

I think this needs clarification.

**Comment by DLu** [comment]
That is valid. Please open a PR that removes max_angle from the dynamic reconfigure configuration.

**Comment by nxdefiant** [comment]
#38 as ordered :)
