### ISSUE TITLE
range_sensor_layer not work in Rviz

### ISSUE THREAD

**Issue by guchaojie** [DLu/navigation_layers#37]
My environment : Ubuntu 16.04 kinetic 
Load range_sensor plugin into costmap_2d:
range_sensor_layer /home/ros/catkin_ws/src/navigation_layers/range_sensor_layer/costmap_plugins.xml
social_navigation_layers /home/ros/catkin_ws/src/navigation_layers/social_navigation_layers/costmap_plugins.xml
costmap_2d /opt/ros/kinetic/share/costmap_2d/costmap_plugins.xml

in local_costmap_param.yaml , add as below:
 plugins:
    - {name: obstacle_layer,      type: "costmap_2d::ObstacleLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
    - {name: sonar,         type: "range_sensor_layer::RangeSensorLayer"}

The result is:
![screenshot from 2017-09-14 14-23-45](https://user-images.githubusercontent.com/4715382/30415029-bcb64b3e-9958-11e7-99cd-bf4e227f99fc.png)

We can see sonar topic in RVIZ .  However, Why the UltraSonar cannot find any obstacle in the range layer in RVIZ?  Range senor layer seems not work.

**Comment by guchaojie** [comment]
have been fixed ， so close it

**Comment by towersla** [comment]
> have been fixed ， so close it

hello, I  have the same problem,can you tell me how to solve it?
