### ISSUE TITLE
Melodic release please 

### ISSUE THREAD

**Issue by doisyg** [DLu/navigation_layers#41]
Support for the current LTS would be nice!

**Comment by doisyg** [comment]
Now that the navigation stack has been released, would it be possible to release this package too? Thanks!

**Comment by DLu** [comment]
Working on some of the other upstream repos. Update soon.

**Comment by doisyg** [comment]
Thx!

**Comment by DLu** [comment]
https://github.com/ros/rosdistro/pull/19017
