### ISSUE TITLE
[range_sensor_layer] symbol lookup error in Melodic

### ISSUE THREAD

**Issue by doisyg** [DLu/navigation_layers#46]
Hello,
First of all, thanks a lot for releasing to Melodic, I just got the binary from the last sync.
Using a Kinetic working configuration, move_base crash when using a range_sensor_layer (and launch successfully when not):

> /opt/ros/melodic/lib/move_base/move_base: symbol lookup error: /opt/ros/melodic/lib//librange_sensor_layer.so: undefined symbol: _ZN3tf212getTimestampIN13geometry_msgs13PointStamped_ISaIvEEEEERKN3ros4TimeERKT_
> [move_base-5] process has died [pid 11782, exit code 127, cmd /opt/ros/melodic/lib/move_base/move_base /cmd_vel:=/navigation_stack/cmd_vel __name:=move_base __log:=/home/keylo/.ros/log/9b3bf342-bfda-11e8-b44c-a0c5898dc1ce/move_base-5.log].
> log file: /home/keylo/.ros/log/9b3bf342-bfda-11e8-b44c-a0c5898dc1ce/move_base-5*.log
> 

Any idea where it is coming from? Maybe a dependency ? I installed ros-melodic-tf* and ros-melodic-geometry* to be sure

**Comment by doisyg** [comment]
Solved by adding `#include "tf2_geometry_msgs/tf2_geometry_msgs.h"` to range_sensor_layer.h

**Comment by DLu** [comment]
Sorry about that. Can you make a PR?

**Comment by doisyg** [comment]
https://github.com/DLu/navigation_layers/pull/47
Maybe needed in social navigation layer too? I did not check

**Comment by dtaranta** [comment]
> #47
> Maybe needed in social navigation layer too? I did not check

Yeah, same problem with the same solution.
