### ISSUE TITLE
Costmap process dies using Range Sensor Layer

### ISSUE THREAD

**Issue by jtrautmann** [DLu/navigation_layers#49]
Hello,

I'm trying to get the Range Sensor Layer to run under Kinetic. When I start the costmap node, it tells me that it subscribed to the topic, but after that, the process just dies without any error output. I also can't see any of the sensor readings in the costmap visualization in rviz.
The configuration file looks like this:

```
plugins:
  - {name: ultrasonic_layer, type: "range_sensor_layer::RangeSensorLayer"}

ultrasonic_layer:
  topics: ["/<my_robot>/ultrasonic"]

publish_frequency: 1.0
robot_radius: 0.4
rolling_window: true
```

The output in the console:

```
[ INFO] [1542906425.104982858]: Using plugin "ultrasonic_layer"
[ INFO] [1542906425.140869614]: costmap/ultrasonic_layer: ALL as input_sensor_type given
[ INFO] [1542906425.198440501]: RangeSensorLayer: subscribed to topic /<my_robot>/ultrasonic
[costmap_2d-1] process has died [pid 7822, exit code -11, cmd /opt/ros/kinetic/lib/costmap_2d/costmap_2d_node __name:=costmap_2d __log:=/home/<user>/.ros/log/872c6ffa-ee63-11e8-8527-b827ebebf3ed/costmap_2d-1.log].
```

I receive messages under the given topic name which look like this:

```
header: 
  seq: 9157
  stamp: 
    secs: 1542906495
    nsecs: 397895017
  frame_id: "sonar_1_link"
radiation_type: 0
field_of_view: 0.261799395084
min_range: 0.019999999553
max_range: 4.5
range: 1.15199995041
```

There is a path from the frame `sonar_1_link` to `map` in the tf tree and the sensor data also gets visualized correctly in rviz.

**Comment by DLu** [comment]
Are you still experiencing this error?

**Comment by jtrautmann** [comment]
No, it was solved, thank you. If I remember it right, the problem was that my robot wasn't using the topics "cmd_vel" and "odom" because they were in another namespace.
