### ISSUE TITLE
RangeSensorLayerConfig.h: No such file or directory

### ISSUE THREAD

**Issue by simk0024** [DLu/navigation_layers#52]
Hi,  
I add range_sensor_layer to my navigation stack, but I received errors as below when `catkin_make`

```
In file included from /home/prd-robotics/Learning/catkin_ws/src/navigation/costmap_2d/plugins/range_sensor_layer.cpp:2:0:
/home/prd-robotics/Learning/catkin_ws/src/navigation/costmap_2d/include/costmap_2d/range_sensor_layer.h:8:55: fatal error: range_sensor_layer/RangeSensorLayerConfig.h: No such file or directory
```

Please advise

**Comment by DLu** [comment]
Please post this question on answers.ros.org instead. Also, you should be able to build the range_sensor_layer in its own package and not move it into the costmap-2d package.
