### ISSUE TITLE
r.range and r.maxrange

### ISSUE THREAD

**Issue by upuphero** [DLu/navigation_layers#55]
What is the difference between range and max_range. I want to improve the accuracy of the sensor so that I want to limit the range of the sensor.Is there any other solutions to solve the problems of low-level stability

**Comment by DLu** [comment]
There is more information about the [`Range`](http://docs.ros.org/api/sensor_msgs/html/msg/Range.html) message here. The range is the actual reading and the max_range is the theoretical limit.
