### ISSUE TITLE
How to install these plugins?

### ISSUE THREAD

**Issue by Makekihe** [DLu/navigation_layers#60]
How and where do I install these plugins, in order to effectively use them inside my local_costmap.yaml?

Currently I've git cloned the Github project and placed it in the /home folder. Then I'm trying to use them for my local costmap, as can be seen on the following picture:
![Screenshot from 2020-04-06 11-58-30](https://user-images.githubusercontent.com/34446346/78546922-85e50a00-77fe-11ea-9a8d-6f34110fda68.png)

When launching my navigation stack, then I get the following error. Do you have an idea of how to correct this issue? 
![Screenshot from 2020-04-06 11-19-28](https://user-images.githubusercontent.com/34446346/78547072-c2b10100-77fe-11ea-8354-f3f86e3346a2.png)

**Comment by DLu** [comment]
I assume you fixed it yourself?

**Comment by Makekihe** [comment]
Yes I did, thank you!
It was an issue caused by not placing the package inside the correct workspace, and not having the people_msgs package, which apparently came separate (https://github.com/wg-perception/people). 

I'm experiencing another issue however, where when inserting any plugin (includes default) into my local_costmap.yaml (see picture above) the costmap in RViz is registered but doesn't appear for walls/static obstacles, and the topic /move_base/local_costmap/costmap seems to only register zeros. It works fine for the global_costmap.yaml, and I can see that the plugins are used through 'rospram get'.
This is probably not the correct place to ask, but do you know how to correct this issue?

**Comment by DLu** [comment]
Can you open a question on answers.ros.org and link to it here please?

**Comment by Makekihe** [comment]
Question on ros answers:
https://answers.ros.org/question/348776/specifying-plugins-to-local_costmapyaml-causes-it-to-disappear/

**Comment by Thinesh-Kumar-T-M** [comment]
May I know how exactly you solved the Installation issue ?
I'm using ROS noetic

**Comment by Makekihe** [comment]
> May I know how exactly you solved the Installation issue ? I'm using ROS noetic

If you take a look at this link, then you can find a more detailed solution:
https://answers.ros.org/question/348776/specifying-plugins-to-local_costmapyaml-causes-it-to-disappear/

**Comment by Thinesh-Kumar-T-M** [comment]
I tried reading, but still couldn't find a way to get things working.
I need help on how to incorporate the range_sensor_layer plugin on the existing workspace.

**Comment by Makekihe** [comment]
Unfortunately, I no longer have access to the project where this issue originated, so I will not be able to help you any further.

**Comment by Thinesh-Kumar-T-M** [comment]
That's ok, No problem.
Anyways I solved the issue. I had a problem with my workspace, and fixed it.

**Comment by Makekihe** [comment]
Given that you had a similar problem, and found the solution, it might make sense to add a comment with your problem and solution to the link I posted earlier in ROS answers. It could be beneficial for the next person.

**Comment by Thinesh-Kumar-T-M** [comment]
Ok sure .
