### ISSUE TITLE
Available for ROS kinetic?

### ISSUE THREAD

**Issue by iandresolares** [DLu/navigation_layers#61]
Hello,
in the wiki.ros.org documentation of the package appears to have kinetic support, but in github there is no such a brand. I tried installing the melodic one but when building the ws i have some errors:
`/home/andres/catkin_ws/src/social_navigation_layers/src/social_layer.cpp: In member function ‘virtual void social_navigation_layers::SocialLayer::updateBounds(double, double, double, double*, double*, double*, double*)’:
/home/andres/catkin_ws/src/social_navigation_layers/src/social_layer.cpp:51:12: error: ‘class tf::TransformListener’ has no member named ‘transform’
       tf_->transform(pt, opt, global_frame);
            ^
/home/andres/catkin_ws/src/social_navigation_layers/src/social_layer.cpp:59:12: error: ‘class tf::TransformListener’ has no member named ‘transform’
       tf_->transform(pt, opt, global_frame);
            ^
social_navigation_layers/CMakeFiles/social_layers.dir/build.make:62: fallo en las instrucciones para el objetivo 'social_navigation_layers/CMakeFiles/social_layers.dir/src/social_layer.cpp.o'
make[2]: *** [social_navigation_layers/CMakeFiles/social_layers.dir/src/social_layer.cpp.o] Error 1
make[2]: *** Se espera a que terminen otras tareas....
/home/andres/catkin_ws/src/social_navigation_layers/src/passing_layer.cpp: In member function ‘virtual void social_navigation_layers::PassingLayer::updateBounds(double, double, double, double*, double*, double*, double*)’:
/home/andres/catkin_ws/src/social_navigation_layers/src/passing_layer.cpp:39:14: error: ‘class tf::TransformListener’ has no member named ‘transform’
         tf_->transform(pt, opt, global_frame);
              ^
/home/andres/catkin_ws/src/social_navigation_layers/src/passing_layer.cpp:47:14: error: ‘class tf::TransformListener’ has no member named ‘transform’
         tf_->transform(pt, opt, global_frame);
              ^
social_navigation_layers/CMakeFiles/social_layers.dir/build.make:110: fallo en las instrucciones para el objetivo 'social_navigation_layers/CMakeFiles/social_layers.dir/src/passing_layer.cpp.o'
make[2]: *** [social_navigation_layers/CMakeFiles/social_layers.dir/src/passing_layer.cpp.o] Error 1
CMakeFiles/Makefile2:6150: fallo en las instrucciones para el objetivo 'social_navigation_layers/CMakeFiles/social_layers.dir/all'
make[1]: *** [social_navigation_layers/CMakeFiles/social_layers.dir/all] Error 2
Makefile:138: fallo en las instrucciones para el objetivo 'all'
make: *** [all] Error 2
Invoking "make -j4 -l4" failed
`
Regards, 
Andrés

**Comment by iandresolares** [comment]
I have found this closed issue #32 , but still I don't understand how to install it for kinetic.

**Comment by DLu** [comment]
My guess is that you're trying to compile the melodic branch. Can you try again with the indigo branch?

**Comment by iandresolares** [comment]
Yep, that works! Thank you!!
