### ISSUE TITLE
Social Navigation Crush by throwing an exception 'pluginlib::LibraryLoadException

### ISSUE THREAD

**Issue by FrankUn** [DLu/navigation_layers#62]
I was running a simulation on turtlebot3, and i am trying to add the social_navigation_package to it in order to perform a dynamic obstacle avoidance, the following is the crush massage:
(i am using ros kinetic)

`![1481975834](https://user-images.githubusercontent.com/62336156/79593637-5abbbe00-810e-11ea-9021-880de7bef557.jpg)`

[ INFO] [1587140683.364604069, 1579.870000000]: Using plugin "social_layer"
terminate called after throwing an instance of 'pluginlib::LibraryLoadException'
  what():  According to the loaded plugin descriptions the class costmap_2d::social_navigation_layers::ProxemicLayer with base class type costmap_2d::Layer does not exist. Declared types are  costmap_2d::InflationLayer costmap_2d::ObstacleLayer costmap_2d::StaticLayer costmap_2d::VoxelLayer frontier_exploration::BoundedExploreLayer range_sensor_layer::RangeSensorLayer social_navigation_layers::PassingLayer social_navigation_layers::ProxemicLayer
[move_base-4] process has died [pid 24191, exit code -6, cmd /opt/ros/kinetic/lib/move_base/move_base cmd_vel:=/cmd_vel odom:=odom __name:=move_base __log:=/home/frank/.ros/log/e91015ee-80c7-11ea-914f-080027d624a9/move_base-4.log].
log file: /home/frank/.ros/log/e91015ee-80c7-11ea-914f-080027d624a9/move_base-4*.log

Can you please share your insights on this.
Thank you so much in advance.
Regards,
Frank

**Comment by DLu** [comment]
To simplify the error message, 
```
The class costmap_2d::social_navigation_layers::ProxemicLayer ... does not exist. 
Declared types are ...social_navigation_layers::ProxemicLayer
```
Do you see the error?

**Comment by FrankUn** [comment]
Thanks for your reply!

> Declared types are ...social_navigation_layers::ProxemicLayer

actually i try this one first, but it return another error...

> [ INFO] [1587144018.234138513, 1580.427000000]: Using plugin "social_layer"
terminate called after throwing an instance of 'pluginlib::LibraryLoadException'
  what():  Could not find library corresponding to plugin social_navigation_layers::ProxemicLayer. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[move_base-4] process has died [pid 29006, exit code -6, cmd /opt/ros/kinetic/lib/move_base/move_base cmd_vel:=/cmd_vel odom:=odom __name:=move_base __log:=/home/frank/.ros/log/79b8de94-80cf-11ea-914f-080027d624a9/move_base-4.log].
log file: /home/frank/.ros/log/79b8de94-80cf-11ea-914f-080027d624a9/move_base-4*.log

**Comment by DLu** [comment]
If you are compiling from source, make sure you have `source ~/.bashrc` before executing the node.

**Comment by FrankUn** [comment]
Thank you David!
I found that the problem might be i did not compile it correctly, when i run catkin_make again, i get this error:

> [ 94%] Generating EusLisp code from face_detector/FaceDetectorActionResult.msg
/home/frank/catkin_ws/src/navigation_layers/social_navigation_layers/src/social_layer.cpp: In member function ‘virtual void social_navigation_layers::SocialLayer::updateBounds(double, double, double, double*, double*, double*, double*)’:
/home/frank/catkin_ws/src/navigation_layers/social_navigation_layers/src/social_layer.cpp:51:12: error: ‘class tf::TransformListener’ has no member named ‘transform’
       tf_->transform(pt, opt, global_frame);
            ^
/home/frank/catkin_ws/src/navigation_layers/social_navigation_layers/src/social_layer.cpp:59:12: error: ‘class tf::TransformListener’ has no member named ‘transform’
       tf_->transform(pt, opt, global_frame);
            ^
/home/frank/catkin_ws/src/navigation_layers/range_sensor_layer/src/range_sensor_layer.cpp: In member function ‘void range_sensor_layer::RangeSensorLayer::updateCostmap(sensor_msgs::Range&, bool)’:
/home/frank/catkin_ws/src/navigation_layers/range_sensor_layer/src/range_sensor_layer.cpp:253:96: error: no matching function for call to ‘tf::TransformListener::canTransform(std::__cxx11::string&, std_msgs::Header_<std::allocator<void> >::_frame_id_type&, std_msgs::Header_<std::allocator<void> >::_stamp_type&, ros::Duration)’
   if (!tf_->canTransform(global_frame_, in.header.frame_id, in.header.stamp, ros::Duration(0.1)))
                                                                                                ^
In file included from /opt/ros/kinetic/include/costmap_2d/layer.h:43:0,
                 from /opt/ros/kinetic/include/costmap_2d/costmap_layer.h:41,
                 from /home/frank/catkin_ws/src/navigation_layers/range_sensor_layer/include/range_sensor_layer/range_sensor_layer.h:5,
                 from /home/frank/catkin_ws/src/navigation_layers/range_sensor_layer/src/range_sensor_layer.cpp:2:
/opt/ros/kinetic/include/tf/tf.h:202:8: note: candidate: bool tf::Transformer::canTransform(const string&, const string&, const ros::Time&, std::__cxx11::string*) const
   bool canTransform(const std::string& target_frame, const std::string& source_frame,
        ^
/opt/ros/kinetic/include/tf/tf.h:202:8: note:   no known conversion for argument 4 from ‘ros::Duration’ to ‘std::__cxx11::string* {aka std::__cxx11::basic_string<char>*}’
/opt/ros/kinetic/include/tf/tf.h:214:8: note: candidate: bool tf::Transformer::canTransform(const string&, const ros::Time&, const string&, const ros::Time&, const string&, std::__cxx11::string*) const
   bool canTransform(const std::string& target_frame, const ros::Time& target_time,
        ^
/opt/ros/kinetic/include/tf/tf.h:214:8: note:   candidate expects 6 arguments, 4 provided
/home/frank/catkin_ws/src/navigation_layers/range_sensor_layer/src/range_sensor_layer.cpp:261:8: error: ‘class tf::TransformListener’ has no member named ‘transform’
   tf_->transform(in, out, global_frame_);
        ^
/home/frank/catkin_ws/src/navigation_layers/range_sensor_layer/src/range_sensor_layer.cpp:267:8: error: ‘class tf::TransformListener’ has no member named ‘transform’
   tf_->transform(in, out, global_frame_);
        ^

Following the doc on Ros wiki, i have cloned people_mags & easy_markers on my workspace
Is there some package i missed cause this problem ?

Many Thanks,
Frank

**Comment by DLu** [comment]
If you are compiling this package from source and using kinetic, you should use the indigo branch.
