### ISSUE TITLE
Not feeling any changes with the proxemic layer

### ISSUE THREAD

**Issue by iandresolares** [DLu/navigation_layers#64]
Hello,
I've been working on a configuration for the proxemic layer but I can't get any difference between dodging any obstacle and one person. Apparently everything is correct, I can visualize how the cost around the person increases correctly, and how the circle around him varies according to various parameters (in rviz). I have tested with the parameters discussed in this issue: #34 . I am using the teb_local_planner although I have also tried the dwa_local_planner. Any idea what I can be doing wrong? What would be most extreme configuration in order to try to notice any difference in the avoidance?
Thanks!

Andrés

**Comment by DLu** [comment]
Tuning the values is hard. I [published a whole paper about it](http://wustl.probablydavid.com/entry179.html). When it comes down to it, if the values are too high, then the path planner tends to ignore them.

**Comment by iandresolares** [comment]
Hello,
thanks for the answer! I'll take a deep look into it, thanks. I'm closing this issue.

**Comment by DLu** [comment]
Just to be clear, the sentiment was meant to empathize with you, not blow you off. Please let me know if you still find an issue with the code.

**Comment by iandresolares** [comment]
Of course, thank you!! I just didn't know the paper was available, and so I have something to work with now!
