### ISSUE TITLE
ROS2

### ISSUE THREAD

**Issue by pavloblindnology** [DLu/navigation_layers#65]
Hi,
Is there any plans to migrate to ROS2?
Thanks.

**Comment by DLu** [comment]
I believe range sensor layer is already ported. I don't know of anyone working on a port of the social layers.

**Comment by iLanceS** [comment]
we also need it for ros foxy,can any one could help me?

**Comment by amjack0** [comment]
How do I install the `range_sensor_layer `for Noetic ?

**Comment by DLu** [comment]
The package is [already available for ROS 2](https://github.com/ros-planning/navigation2/blob/main/nav2_costmap_2d/plugins/range_sensor_layer.cpp). For Noetic, please open a separate issue.
