### ISSUE TITLE
catkin_make problem

### ISSUE THREAD

**Issue by CarazyR** [DLu/navigation_layers#72]
when I catkin_make the package, there are a lot of error like this:
/home/robot/catkin_ws/src/navigation_layers/social_navigation_layers/src/social_layer.cpp:61:12: error: ‘class tf::TransformListener’ has no member named ‘transform’

Ubuntu 16.04 + ROS kinetic

Can you give me some advice about it?

**Comment by CarazyR** [comment]
I see the issues #32  use the old version, and the error change.
/home/robot/catkin_ws/src/navigation_layers/range_sensor_layer/src/range_sensor_layer.cpp:69:30: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   for (unsigned int i = 0; i < topic_names.size(); i++)
                              ^
/home/robot/catkin_ws/src/navigation_layers/range_sensor_layer/src/range_sensor_layer.cpp: In member function ‘void range_sensor_layer::RangeSensorLayer::reconfigureCB(range_sensor_layer::RangeSensorLayerConfig&, uint32_t)’:
/home/robot/catkin_ws/src/navigation_layers/range_sensor_layer/src/range_sensor_layer.cpp:156:23: error: ‘class range_sensor_layer::RangeSensorLayerConfig’ has no member named ‘max_angle’
   max_angle_ = config.max_angle;
                       ^
cc1plus: all warnings being treated as errors

**Comment by DLu** [comment]
@CarazyR 
There was a change in the ROS Navigation API in Melodic where [layers started to use tf2.](https://github.com/ros-planning/navigation/pull/755)

As a result, it is important that you check out the proper version of this repo for Kinetic. The default branch is `melodic`, but for `kinetic` you'll want `indigo` (which is valid for `indigo`, `jade`, `kinetic` and `lunar`)

Please let me know if switching the branch fixes your problems. There may be other errors due to different levels of strictness.

**Comment by CarazyR** [comment]
I am very glad to receive your reply.As a student, I really admire the work you do.I checked closed issues and I refer to https://github.com/ros/rosdistro/pull/13364. And use version 3.1.0, successfully compiled. In addition, I want to generate a costmap with different shapes for a given coordinate. Is there any relevant tutorial? Thank you very much.

**Comment by g4h** [comment]
Hi，dear @Dlu，I found same error as CarayR，when i compile range_sensor_layer in ubuntu16.04 +kinetic. And then  I change branch of indigo ，i found another error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   for (unsigned int i = 0; i < topic_names.size(); i++).

Looking forward to your reply，thank you！

**Comment by DLu** [comment]
Pretty sure this is closed now that I fixed #74. Please let me know if you still have problems.
