### ISSUE TITLE
 Plugin range_sensor_layer won't compile. not found RangeSensorLayerConfig.h

### ISSUE THREAD

**Issue by dragonknight321** [DLu/navigation_layers#80]
When compiling, it writes that the RangeSensorLayerConfig.h header file was not found. But he is not in the repository either. What can be wrong?

**Comment by ju-mingyue** [comment]
@dragonknight321 
I don’t know what version of ros you are using. Currently I am using melodic. My compilation method is to download the compressed package of navigation_layer in the link below.
[https://github.com/DLu/navigation_layers](url)

Then copy the compressed package to the src file in your working directory, and extract the range_sensor_layer folder in the compressed package separately.

If there is an rtabmap_ros file in the src file in your workspace, the compilation may fail.

**Comment by DLu** [comment]
That header file is generated using [dynamic reconfigure](http://wiki.ros.org/dynamic_reconfigure)
