### ISSUE TITLE
About ultrasound cannot be added to the costmap

### ISSUE THREAD

**Issue by ju-mingyue** [DLu/navigation_layers#82]
@DLu 
I am honored to see your message, I have a question about this and I need to trouble you.
I have a problem when using ultrasound to avoid obstacles. My configuration in the local_costmap is as follows:

![深度截图_选择区域_20210715134226](https://user-images.githubusercontent.com/81499872/125735000-c0333dd5-76c6-4177-9073-a5c82f276b38.png)
![深度截图_选择区域_20210715134205](https://user-images.githubusercontent.com/81499872/125735009-2169868f-b0e6-4ba4-b465-ec3e6404258d.png)

The ros version I use is melodic. I have successfully configured range_sensor_layer in it, but now ultrasound cannot add obstacles to my local map, as shown in the following figure:
![深度截图_选择区域_20210715134636](https://user-images.githubusercontent.com/81499872/125735348-9f77c0ac-b4e3-4147-8a65-7bfbb3f9c95e.png)

I use rostopic echo to view the published topic, but I can find the message in the topic.Here is the procedure I used to publish ultrasound topic.
`
    #!/usr/bin/env python3
    # -*- coding: utf-8 -*-
    
    import rospy
    from serial import Serial
    import serial.tools.list_ports
    from sensor_msgs.msg import Range
    from std_msgs.msg import Header
    import struct
    
    import math 
    import os,sys
    import time
    import threading
    
    
    x=serial.Serial('/dev/Ultrasound',9600)
    def faSong():   
        while True: 
              
            myinput=b'\xb4\x01'    
            x.write(myinput)    
            time.sleep(0.2)     
            #print(x)
    def jieShou():  
        while True: 
            while x.inWaiting()>0:  
                myout=x.read(24) 
                #print (myout)
                datas=''.join(map(lambda x:('/x' if len(hex(x))>=4 else '/x0')+hex(x)[2:],myout))
                #print(datas)
                new_datas=datas[2:].split('/x') 
                need=''.join(new_datas) 
               
                print(need)
                data_1=float(need[4]+need[5]+need[6]+need[7])/1000
                data_2=float(need[16]+need[17]+need[18]+need[19])/1000
                data_3=float(need[28]+need[29]+need[30]+need[31])/1000
                data_4=float(need[40]+need[41]+need[42]+need[43])/1000
               
                print(data_1,data_2,data_3,data_4)
                msg1=Range()
                msg2=Range()
                msg3=Range()
                msg4=Range()
    
                header1=Header()
                header2=Header()
                header3=Header()
                header4=Header()
    
                header1.stamp=rospy.Time.now()
                header2.stamp=rospy.Time.now()
                header3.stamp=rospy.Time.now()
                header4.stamp=rospy.Time.now()
    
                header1.frame_id="/ultrasound1"
                header2.frame_id="/ultrasound2"
                header3.frame_id="/ultrasound3"
                header4.frame_id="/ultrasound4"
    
                msg1.header=header1
                msg2.header=header2
                msg3.header=header3
                msg4.header=header4
    
                msg1.field_of_view=1
                msg2.field_of_view=1
                msg3.field_of_view=1
                msg4.field_of_view=1
    
                msg1.min_range=0.25
                msg2.min_range=0.25
                msg3.min_range=0.25
                msg4.min_range=0.25
    
                msg1.max_range=1.5
                msg2.max_range=1.5
                msg3.max_range=1.5
                msg4.max_range=1.5
    
                msg1.range=data_1
                msg2.range=data_2
                msg3.range=data_3
                msg4.range=data_4
    
                global cmd_pub1,cmd_pub2,cmd_pub3,cmd_pub4
                cmd_pub1.publish(msg1)
                cmd_pub2.publish(msg2)
                cmd_pub3.publish(msg3)
                cmd_pub4.publish(msg4)
    if __name__ == '__main__':
        rospy.init_node('ultrasonic')
        global cmd_pub1,cmd_pub2,cmd_pub3,cmd_pub4
        cmd_pub1 = rospy.Publisher('ultrasoundpublisher1',Range,queue_size=1)
        cmd_pub2 = rospy.Publisher('ultrasoundpublisher2',Range,queue_size=1)
        cmd_pub3 = rospy.Publisher('ultrasoundpublisher3',Range,queue_size=1)
        cmd_pub4 = rospy.Publisher('ultrasoundpublisher4',Range,queue_size=1)
        t1=threading.Thread(target=jieShou)
        t2=threading.Thread(target=faSong)
        t2.start()
        t1.start()
`
I don't know where the problem is now, so I really hope to get your help.

**Comment by HappySamuel** [comment]
Hi @ju-mingyue 
Can share how do you get the sensor_msgs::range to be registered into costmap? I have been following the http://wiki.ros.org/range_sensor_layer , but without any success. 

Can i have a look at your range_sensor_layer settings? Perhaps i will be able to have ultrasonic sensors to run successfully.

Best,
Samuel
