### ISSUE TITLE
Indigo release

### ISSUE THREAD

**Issue by bit-pirate** [DLu/navigation_layers#9]
Is there a plan for an Indigo release?

**Comment by DLu** [comment]
hydro branch builds fine in indigo. Will try to make the release sometime this week?

**Comment by bit-pirate** [comment]
> hydro branch builds fine in indigo.

Also runs fine! Great work!

> Will try to make the release sometime this week?

Awesome. No need to hurry.

**Comment by DLu** [comment]
Will be present in the next release!

**Comment by bit-pirate** [comment]
:+1: Thanks a lot!
